# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'win1803'

variables:
  imageName: 'athens-win-test:$(build.buildId)'

steps:
- script: |
    echo "docker build"
    docker build --isolation=hyperv -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
